-- Gerado por Oracle SQL Developer Data Modeler 4.1.2.1.899
--   em:        2015-12-18 17:45:05 BRST
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE TB_LANCA_ARQUIVO
  (
    ID              INTEGER NOT NULL ,
    ID_ARQU_REMESSA INTEGER NOT NULL ,
    TP_ARQUIVO NCHAR (3) ,
    DT_ENVIO       DATE ,
    DT_RECEBIMENTO INTEGER ,
    NM_CAMINHO_ARQUIVO NVARCHAR2 (249)
  ) ;
CREATE INDEX TB_LANCA_ARQUIVO__IDX ON TB_LANCA_ARQUIVO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_ARQUIVO ADD CONSTRAINT TB_LANCA_ARQUIVO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_AVALIACAO
  (
    ID                INTEGER NOT NULL ,
    ID_AVALIACAO_ROOT INTEGER NOT NULL ,
    ID_USU_AVALIADOR  INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (250) ,
    DT_AVALIACAO DATE ,
    SN_STATUS    CHAR (1)
  ) ;
CREATE INDEX TB_LANCA_AVALIACAO__IDX ON TB_LANCA_AVALIACAO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_AVALIACAO ADD CONSTRAINT TB_LANCA_AVALIACAO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_BOLETO
  (
    ID            INTEGER NOT NULL ,
    DT_GERACAO    DATE ,
    DT_VENCIMENTO DATE ,
    VL_VALOR      NUMBER (10,2) ,
    LO_DESCRICAO CLOB ,
    CD_CAMINHO_BOLETO NVARCHAR2 (250)
  ) ;
CREATE INDEX TB_LANCA_BOLETO__IDX ON TB_LANCA_BOLETO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_BOLETO ADD CONSTRAINT TB_LANCA_BOLETO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_CLIENTE
  (
    ID INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (1) ,
    CD_FORNECEDOR INTEGER
  ) ;
CREATE INDEX TB_LANCA_CLIENTE__IDX ON TB_LANCA_CLIENTE
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_CLIENTE ADD CONSTRAINT TB_LANCA_CLIENTE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_CLIENTE_SETOR
  (
    ID         INTEGER NOT NULL ,
    ID_CLIENTE INTEGER NOT NULL ,
    ID_SETOR   INTEGER NOT NULL
  ) ;
ALTER TABLE TB_LANCA_CLIENTE_SETOR ADD CONSTRAINT TB_LANCA_CLIENTE_SETOR_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_CONTRATO
  (
    ID         INTEGER NOT NULL ,
    ID_CLIENTE INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (220) ,
    DT_INICIO   DATE ,
    DT_FINAL    DATE ,
    DT_REAJUSTE DATE
  ) ;
CREATE INDEX TB_CONTRATO__IDX ON TB_LANCA_CONTRATO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_CONTRATO ADD CONSTRAINT TB_CONTRATO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_LANCAMENTO
  (
    ID              INTEGER NOT NULL ,
    ID_CONTRATO     INTEGER NOT NULL ,
    ID_SERVICO      INTEGER NOT NULL ,
    ID_USU_CONTRATO INTEGER NOT NULL ,
    ID_USU_LANCADOR INTEGER NOT NULL ,
    ID_AVALICAO     INTEGER NOT NULL ,
    VL_LANCAMENTO   NUMBER (10,2) ,
    VL_FIXO         NUMBER (10,2) ,
    VL_VARIAVEL     NUMBER (10,2) ,
    DT_LANCAMENTO   DATE ,
    DT_COMPETENCIA  DATE
  ) ;
CREATE INDEX TB_LANCA_LANCAMENTO__IDX ON TB_LANCA_LANCAMENTO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT TB_LANCA_LANCAMENTO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_LANCAMENTO_BOLETO
  (
    ID            INTEGER NOT NULL ,
    ID_BOLETO     INTEGER NOT NULL ,
    ID_LANCAMENTO INTEGER NOT NULL
  ) ;
CREATE INDEX TB_LNC_LNC_BLT__IDX ON TB_LANCA_LANCAMENTO_BOLETO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_LANCAMENTO_BOLETO ADD CONSTRAINT TB_LANCA_LANCAMENTO_BOLETO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_SERVICO
  (
    ID            INTEGER NOT NULL ,
    ID_TP_SERVICO INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (250) ,
    CD_HISTORICO_PADRAO INTEGER ,
    CD_TP_DOCUMENTO     INTEGER ,
    CD_CONTA_CONTABIL   INTEGER ,
    CD_CONTA_RESULTADO  INTEGER ,
    CD_CONTA_CUSTO      INTEGER
  ) ;
CREATE INDEX TB_SERVICO__IDX ON TB_LANCA_SERVICO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_SERVICO ADD CONSTRAINT TB_LANCA_SERVICO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_SERVICO_CONTRATO
  (
    ID          INTEGER NOT NULL ,
    ID_SERVICO  INTEGER NOT NULL ,
    ID_CONTRATO INTEGER NOT NULL ,
    VL_SERVICO  NUMBER (10,2)
  ) ;
CREATE INDEX TB_LANCA_SERVICO_CONTRATO__IDX ON TB_LANCA_SERVICO_CONTRATO
  (
    ID ASC
  ) ;
ALTER TABLE TB_LANCA_SERVICO_CONTRATO ADD CONSTRAINT TB_LANCA_SERVICO_CONTRATO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_SERVICO_USUARIO
  (
    ID         INTEGER NOT NULL ,
    ID_SERVICO INTEGER NOT NULL ,
    ID_USUARIO INTEGER NOT NULL
  ) ;
CREATE INDEX TB_LANCA_SERVICO_USUARIO__IDX ON TB_LANCA_SERVICO_USUARIO
  (
    ID ASC
  ) ;
ALTER TABLE TB_LANCA_SERVICO_USUARIO ADD CONSTRAINT TB_LANCA_SERVICO_USUARIO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_SETOR
  (
    ID INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (245) ,
    LO_DETALHES CLOB ,
    VL_AREA NUMBER (10,2)
  ) ;
CREATE INDEX TB_LANCA_SETOR__IDX ON TB_LANCA_SETOR
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_SETOR ADD CONSTRAINT TB_LANCA_SETOR_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_TIPO_SERVICO
  (
    ID INTEGER NOT NULL ,
    NM_TITULO NVARCHAR2 (250) ,
    SN_COBRA_SETOR CHAR (1)
  ) ;
COMMENT ON COLUMN TB_LANCA_TIPO_SERVICO.SN_COBRA_SETOR
IS
  'INDICA QUE O SERVIÇO DEVE SER COBRADO POR SETOR' ;
ALTER TABLE TB_LANCA_TIPO_SERVICO ADD CONSTRAINT TB_LANCA_TIPO_SERVICO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_TRANSMISSAO
  (
    ID             INTEGER NOT NULL ,
    ID_ARQUIVO     INTEGER NOT NULL ,
    DT_TRANSMISSAO DATE
  ) ;
CREATE INDEX TB_LANCA_TRANSMISSAO__IDX ON TB_LANCA_TRANSMISSAO
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_TRANSMISSAO ADD CONSTRAINT TB_LANCA_TRANSMISSAO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_TRANS_LANC
  (
    ID             INTEGER NOT NULL ,
    ID_TRANSMISSAO INTEGER NOT NULL ,
    ID_LANCAMENTO  INTEGER NOT NULL
  ) ;
CREATE INDEX TB_LANCA_TRANS_LANC__IDX ON TB_LANCA_TRANS_LANC
  ( ID ASC
  ) ;
ALTER TABLE TB_LANCA_TRANS_LANC ADD CONSTRAINT TB_LANCA_TRANS_LANC_PK PRIMARY KEY ( ID ) ;


CREATE TABLE TB_LANCA_USUARIO
  (
    ID          INTEGER NOT NULL ,
    ID_USER_PTC INTEGER NOT NULL ,
    CD_PERFIL   CHAR (1) NOT NULL
  ) ;
COMMENT ON COLUMN TB_LANCA_USUARIO.CD_PERFIL
IS
  'A = Administrador; G = Gestores; C = Controladoria; F = Financeiro' ;
  CREATE INDEX TB_LANCA_USUARIO__IDX ON TB_LANCA_USUARIO
    ( ID ASC
    ) ;
ALTER TABLE TB_LANCA_USUARIO ADD CONSTRAINT TB_LANCA_USUARIO_PK PRIMARY KEY ( ID ) ;



ALTER TABLE TB_LANCA_ARQUIVO ADD CONSTRAINT ID_ARQUIVO_FK FOREIGN KEY ( ID_ARQU_REMESSA ) REFERENCES TB_LANCA_ARQUIVO ( ID ) ;

ALTER TABLE TB_LANCA_TRANSMISSAO ADD CONSTRAINT ID_ARQUIVO_FKv2 FOREIGN KEY ( ID_ARQUIVO ) REFERENCES TB_LANCA_ARQUIVO ( ID ) ;

ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT ID_AVALIACAO_FK FOREIGN KEY ( ID_AVALICAO ) REFERENCES TB_LANCA_AVALIACAO ( ID ) ;

ALTER TABLE TB_LANCA_AVALIACAO ADD CONSTRAINT ID_AVALIACAO_ROOT_FK FOREIGN KEY ( ID_AVALIACAO_ROOT ) REFERENCES TB_LANCA_AVALIACAO ( ID ) ;

ALTER TABLE TB_LANCA_LANCAMENTO_BOLETO ADD CONSTRAINT ID_BOLETO_FK FOREIGN KEY ( ID_BOLETO ) REFERENCES TB_LANCA_BOLETO ( ID ) ;

ALTER TABLE TB_LANCA_CLIENTE_SETOR ADD CONSTRAINT ID_CLIENTE_FK FOREIGN KEY ( ID_CLIENTE ) REFERENCES TB_LANCA_CLIENTE ( ID ) ;

ALTER TABLE TB_LANCA_CONTRATO ADD CONSTRAINT ID_CLIENTE_FKv2 FOREIGN KEY ( ID_CLIENTE ) REFERENCES TB_LANCA_CLIENTE ( ID ) ;

ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT ID_CONTRATO_FK FOREIGN KEY ( ID_CONTRATO ) REFERENCES TB_LANCA_CONTRATO ( ID ) ;

ALTER TABLE TB_LANCA_SERVICO_CONTRATO ADD CONSTRAINT ID_CONTRATO_FKv2 FOREIGN KEY ( ID_CONTRATO ) REFERENCES TB_LANCA_CONTRATO ( ID ) ;

ALTER TABLE TB_LANCA_LANCAMENTO_BOLETO ADD CONSTRAINT ID_LANCAMENTO_FK FOREIGN KEY ( ID_LANCAMENTO ) REFERENCES TB_LANCA_LANCAMENTO ( ID ) ;

ALTER TABLE TB_LANCA_TRANS_LANC ADD CONSTRAINT ID_LANCAMENTO_FKv2 FOREIGN KEY ( ID_LANCAMENTO ) REFERENCES TB_LANCA_LANCAMENTO ( ID ) ;

ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT ID_SERVICO_FK FOREIGN KEY ( ID_SERVICO ) REFERENCES TB_LANCA_SERVICO ( ID ) ;

ALTER TABLE TB_LANCA_SERVICO_CONTRATO ADD CONSTRAINT ID_SERVICO_FKv2 FOREIGN KEY ( ID_SERVICO ) REFERENCES TB_LANCA_SERVICO ( ID ) ;

ALTER TABLE TB_LANCA_SERVICO_USUARIO ADD CONSTRAINT ID_SERVICO_FKv3 FOREIGN KEY ( ID_SERVICO ) REFERENCES TB_LANCA_SERVICO ( ID ) ;

ALTER TABLE TB_LANCA_CLIENTE_SETOR ADD CONSTRAINT ID_SETOR_FK FOREIGN KEY ( ID_SETOR ) REFERENCES TB_LANCA_SETOR ( ID ) ;

ALTER TABLE TB_LANCA_SERVICO ADD CONSTRAINT ID_TP_SERVICO_FK FOREIGN KEY ( ID_TP_SERVICO ) REFERENCES TB_LANCA_TIPO_SERVICO ( ID ) ;

ALTER TABLE TB_LANCA_TRANS_LANC ADD CONSTRAINT ID_TRANSMISSAO_FK FOREIGN KEY ( ID_TRANSMISSAO ) REFERENCES TB_LANCA_TRANSMISSAO ( ID ) ;

ALTER TABLE TB_LANCA_USUARIO ADD CONSTRAINT ID_USER_PTC_FK FOREIGN KEY ( ID_USER_PTC ) REFERENCES TB_PTC_USUARIO_PUSER ( ID_PUSER ) ;

ALTER TABLE TB_LANCA_SERVICO_USUARIO ADD CONSTRAINT ID_USUARIO_FK FOREIGN KEY ( ID_USUARIO ) REFERENCES TB_LANCA_USUARIO ( ID ) ;

ALTER TABLE TB_LANCA_AVALIACAO ADD CONSTRAINT ID_USU_AVALIADOR_FK FOREIGN KEY ( ID_USU_AVALIADOR ) REFERENCES TB_PTC_USUARIO_PUSER ( ID_PUSER ) ;

ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT ID_USU_CONTRATO_FK FOREIGN KEY ( ID_USU_CONTRATO ) REFERENCES TB_PTC_USUARIO_PUSER ( ID_PUSER ) ;

ALTER TABLE TB_LANCA_LANCAMENTO ADD CONSTRAINT ID_USU_LANCADOR_FK FOREIGN KEY ( ID_USU_LANCADOR ) REFERENCES TB_PTC_USUARIO_PUSER ( ID_PUSER ) ;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                            14
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
